;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagList=(Tag="Ability.Fail.Stamina",DevComment="")
+GameplayTagList=(Tag="Ability.Melee.Light",DevComment="")
+GameplayTagList=(Tag="Cooldown.HitReact",DevComment="")
+GameplayTagList=(Tag="Damage.Physical",DevComment="")
+GameplayTagList=(Tag="Data.Damage",DevComment="")
+GameplayTagList=(Tag="Data.StaminaCost",DevComment="")
+GameplayTagList=(Tag="Event.MeleeHitWindow",DevComment="")
+GameplayTagList=(Tag="Event.ReceivedHit",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Hit.Melee",DevComment="")
+GameplayTagList=(Tag="GameplayCue.HitReact.Melee",DevComment="")
+GameplayTagList=(Tag="State.Attacking",DevComment="")
+GameplayTagList=(Tag="State.Sprinting",DevComment="")

